# Codecov configuration
# See https://docs.codecov.com/docs/codecov-yaml

codecov:
  token: # Set in repository secrets
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
        branches: null
    patch:
      default:
        target: 70%
        threshold: 1%

comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: no

flags:
  unittests:
    paths:
      - agent_chaos_sdk/
    carryforward: true

