from enum import Enum


class ErrorCode(str, Enum):
    JSON_DECODE_ERROR = "JSON_DECODE_ERROR"
    MUTATION_FAILED = "MUTATION_FAILED"
    INVALID_JSONPATH = "INVALID_JSONPATH"
    STRATEGY_DISABLED = "STRATEGY_DISABLED"
    CONFIG_INVALID = "CONFIG_INVALID"
    CLASSIFIER_STRICT_MISSING_RULES = "CLASSIFIER_STRICT_MISSING_RULES"
